---
services:
  - docker

script:
  - sudo mkdir -p /srv/{tv_shows,movies,downloads}
  - docker-compose up -d --build
  - sleep 20
  - curl -o /dev/null -sfL http://localhost/series
  - curl -o /dev/null -sfL http://localhost/movies
  - curl -o /dev/null -sfL -u nzbget:tegbzn6789 http://localhost/nzb
  - curl -sfL http://localhost/torrent | grep -q "Transmission Web Interface"
  - curl -sfL http://localhost/aggregator/torrent | grep -q "Jackett"
  - curl -sfL http://localhost/aggregator/nzb | grep -q "NZB Hydra"
