version: '3'
services:
  proxy:
    image: nginx:1.13-alpine
    ports:
      - "80:80"
    volumes:
      - ./files/downloader.conf:/etc/nginx/conf.d/default.conf:ro

  series:
    environment:
      TZ: "America/Toronto"
    image: linuxserver/sonarr:107
    volumes:
      - sonarr_config:/config
      # where the tv shows are stored after being processed
      - series:/tv
      # where the downloads are stored
      - downloads:/downloads

  movies:
    environment:
      TZ: "America/Toronto"
    image: linuxserver/radarr:78
    volumes:
      - radarr_config:/config
      - movies:/movies
      - downloads:/downloads

  nzb:
    environment:
      TZ: "America/Toronto"
    image: linuxserver/nzbget:100
    volumes:
      - nzbget_config:/config
      - downloads:/downloads

  torrent:
    environment:
      TZ: "America/Toronto"
    image: linuxserver/transmission:103
    ports:
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - transmission_config:/config
      - downloads:/downloads
      # optional watch folder not configured

volumes:
  sonarr_config:
  radarr_config:
  nzbget_config:
  transmission_config:
  series:
    driver_opts:
      type: none
      o: bind
      # mapping to a separate dir to customize which physical drive the data is
      # on. the os might be on a smaller ssd but have another hdd available to
      # store medias on
      device: /srv/tv_shows
  movies:
    driver_opts:
      type: none
      o: bind
      # mapping to a separate dir to customize which physical drive the data is
      # on. the os might be on a smaller ssd but have another hdd available to
      # store medias on
      device: /srv/movies
  downloads:
    driver_opts:
      type: none
      o: bind
      # mapping to a separate dir to customize which physical drive the data is
      # on. the os might be on a smaller ssd but have another hdd available to
      # store medias on
      device: /srv/downloads
