version: '3'
services:
  tv:
    environment:
      TZ: "America/Toronto"
    image: linuxserver/sonarr
    ports:
      - "8989:8989"
    volumes:
      - sonarr_config:/config
      # where the tv shows are stored after being processed
      - tv:/tv
      # where the downloads are stored
      - downloads:/downloads

  movies:
    environment:
      TZ: "America/Toronto"
    image: linuxserver/couchpotato
    ports:
      - "5050:5050"
    volumes:
      - couchpotato_config:/config
      - movies:/movies
      - downloads:/downloads

  nzb:
    environment:
      TZ: "America/Toronto"
    image: linuxserver/nzbget
    ports:
      - "6789:6789"
    volumes:
      - nzbget_config:/config
      - downloads:/downloads

  torrent:
    environment:
      TZ: "America/Toronto"
    image: linuxserver/transmission
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - transmission_config:/config
      - downloads:/downloads
      # optional watch folder not configured

volumes:
  sonarr_config:
  couchpotato_config:
  nzbget_config:
  transmission_config:
  tv:
    driver_opts:
      type: none
      o: bind
      # the docker host's ssd is too small for all this data
      device: /media/storage/nas/TV
  movies:
    driver_opts:
      type: none
      o: bind
      # the docker host's ssd is too small for all this data
      device: /media/storage/nas/Movies
  downloads:
    driver_opts:
      type: none
      o: bind
      # the docker host's ssd is too small for all this data
      device: /media/storage/downloads
